export interface ProfileTheme {
  id: string;
  name: string;
  description: string;
  animationLabel: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  bgBase: string;
  cardBg: string;
  cardBorder: string;
  textColor: string;
  textSecondaryColor: string;
}

export const PROFILE_THEMES: ProfileTheme[] = [
  {
    id: 'matrix',
    name: 'Matrix',
    description: 'Green falling code, black background',
    animationLabel: 'Green falling code',
    primaryColor: '#00FF66',
    secondaryColor: '#008F11',
    accentColor: '#00FF66',
    bgBase: '#020A04',
    cardBg: 'rgba(6, 24, 12, 0.78)',
    cardBorder: 'rgba(0, 255, 102, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#7DFFB3',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon city, moving lights',
    animationLabel: 'Neon city, moving lights',
    primaryColor: '#00F0FF',
    secondaryColor: '#FF007F',
    accentColor: '#FFE600',
    bgBase: '#0D0818',
    cardBg: 'rgba(24, 12, 38, 0.80)',
    cardBorder: 'rgba(0, 240, 255, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#00F0FF',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Flowing aurora lights',
    animationLabel: 'Flowing aurora lights',
    primaryColor: '#00FFC2',
    secondaryColor: '#8A2BE2',
    accentColor: '#00E5FF',
    bgBase: '#040F1E',
    cardBg: 'rgba(8, 26, 44, 0.78)',
    cardBorder: 'rgba(0, 255, 194, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#80FFE1',
  },
  {
    id: 'starfield',
    name: 'Starfield',
    description: 'Stars move slowly',
    animationLabel: 'Stars move slowly',
    primaryColor: '#FFFFFF',
    secondaryColor: '#7B68EE',
    accentColor: '#E0E7FF',
    bgBase: '#040612',
    cardBg: 'rgba(12, 16, 36, 0.80)',
    cardBorder: 'rgba(224, 231, 255, 0.22)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#C7D2FE',
  },
  {
    id: 'nebula',
    name: 'Nebula',
    description: 'Cosmic gas clouds flow',
    animationLabel: 'Cosmic gas clouds flow',
    primaryColor: '#E056FD',
    secondaryColor: '#686DE0',
    accentColor: '#F368E0',
    bgBase: '#0C041C',
    cardBg: 'rgba(28, 12, 48, 0.80)',
    cardBorder: 'rgba(224, 86, 253, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#E8BCFF',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Water waves / light reflections',
    animationLabel: 'Water waves / light reflections',
    primaryColor: '#00D2D3',
    secondaryColor: '#0984E3',
    accentColor: '#48DBFB',
    bgBase: '#03192B',
    cardBg: 'rgba(6, 32, 54, 0.80)',
    cardBorder: 'rgba(0, 210, 211, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#7EEBF2',
  },
  {
    id: 'rainy_window',
    name: 'Rainy Window',
    description: 'Rain drops on glass',
    animationLabel: 'Rain drops on glass',
    primaryColor: '#74B9FF',
    secondaryColor: '#4834D4',
    accentColor: '#81ECEC',
    bgBase: '#0F1722',
    cardBg: 'rgba(22, 33, 48, 0.80)',
    cardBorder: 'rgba(116, 185, 255, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#B4D8FF',
  },
  {
    id: 'fire',
    name: 'Fire',
    description: 'Slow-moving flames',
    animationLabel: 'Slow-moving flames',
    primaryColor: '#FF7675',
    secondaryColor: '#F0932B',
    accentColor: '#FFBE76',
    bgBase: '#190805',
    cardBg: 'rgba(42, 16, 10, 0.80)',
    cardBorder: 'rgba(255, 118, 117, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FFC4A8',
  },
  {
    id: 'snowfall',
    name: 'Snowfall',
    description: 'Snowflakes fall',
    animationLabel: 'Snowflakes fall',
    primaryColor: '#E4F1FE',
    secondaryColor: '#74B9FF',
    accentColor: '#A0C4FF',
    bgBase: '#0C1829',
    cardBg: 'rgba(18, 32, 54, 0.80)',
    cardBorder: 'rgba(228, 241, 254, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#CBE3FD',
  },
  {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    description: 'Flying sakura petals',
    animationLabel: 'Flying sakura petals',
    primaryColor: '#FFAAA7',
    secondaryColor: '#FF7597',
    accentColor: '#FFD3B6',
    bgBase: '#1E0E18',
    cardBg: 'rgba(44, 20, 36, 0.80)',
    cardBorder: 'rgba(255, 170, 167, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FFCCD2',
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description: 'Spinning star/planet effects',
    animationLabel: 'Spinning star/planet effects',
    primaryColor: '#BDC581',
    secondaryColor: '#82589F',
    accentColor: '#F8A5C2',
    bgBase: '#060317',
    cardBg: 'rgba(20, 12, 42, 0.80)',
    cardBorder: 'rgba(189, 197, 129, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#DDD6FE',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    description: 'Retro grid + sun + moving horizon',
    animationLabel: 'Retro grid + sun + moving horizon',
    primaryColor: '#FD79A8',
    secondaryColor: '#6C5CE7',
    accentColor: '#FEEAA7',
    bgBase: '#1B092A',
    cardBg: 'rgba(38, 16, 56, 0.80)',
    cardBorder: 'rgba(253, 121, 168, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FFB8D2',
  },
  {
    id: 'glitch',
    name: 'Glitch',
    description: 'Occasional digital glitch',
    animationLabel: 'Occasional digital glitch',
    primaryColor: '#00CEC9',
    secondaryColor: '#D63031',
    accentColor: '#55EFC4',
    bgBase: '#0E0F14',
    cardBg: 'rgba(22, 24, 32, 0.82)',
    cardBorder: 'rgba(0, 206, 201, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#81ECEC',
  },
  {
    id: 'electric',
    name: 'Electric',
    description: 'Background electric/plasma effects',
    animationLabel: 'Background electric/plasma effects',
    primaryColor: '#A29BFE',
    secondaryColor: '#0984E3',
    accentColor: '#70A1FF',
    bgBase: '#08051E',
    cardBg: 'rgba(20, 16, 48, 0.80)',
    cardBorder: 'rgba(162, 155, 254, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#C4B5FD',
  },
  {
    id: 'particles',
    name: 'Particles',
    description: 'Slow-floating particles around the user',
    animationLabel: 'Slow-floating particles around the user',
    primaryColor: '#FFEAA7',
    secondaryColor: '#00CEC9',
    accentColor: '#FDCB6E',
    bgBase: '#0A0F17',
    cardBg: 'rgba(18, 25, 36, 0.80)',
    cardBorder: 'rgba(255, 234, 167, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FFF0C2',
  },
  {
    id: 'liquid_metal',
    name: 'Liquid Metal',
    description: 'Metallic liquid flow',
    animationLabel: 'Metallic liquid flow',
    primaryColor: '#DFE6E9',
    secondaryColor: '#B2BEC3',
    accentColor: '#FFFFFF',
    bgBase: '#111419',
    cardBg: 'rgba(28, 32, 40, 0.82)',
    cardBorder: 'rgba(223, 230, 233, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#D1D5DB',
  },
  {
    id: 'hologram',
    name: 'Hologram',
    description: 'Scanline + holographic shimmer',
    animationLabel: 'Scanline + holographic shimmer',
    primaryColor: '#55EFC4',
    secondaryColor: '#81ECEC',
    accentColor: '#00CEC9',
    bgBase: '#03141F',
    cardBg: 'rgba(8, 30, 42, 0.80)',
    cardBorder: 'rgba(85, 239, 196, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#A3F7DF',
  },
  {
    id: 'black_hole',
    name: 'Black Hole',
    description: 'Slow-rotating cosmic effect toward center',
    animationLabel: 'Slow-rotating cosmic effect toward center',
    primaryColor: '#FAB1A0',
    secondaryColor: '#E17055',
    accentColor: '#FFAA00',
    bgBase: '#020205',
    cardBg: 'rgba(16, 12, 20, 0.84)',
    cardBorder: 'rgba(250, 177, 160, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FED7AA',
  },
  {
    id: 'lava_lamp',
    name: 'Lava Lamp',
    description: 'Flowing colorful blobs',
    animationLabel: 'Flowing colorful blobs',
    primaryColor: '#FF7675',
    secondaryColor: '#6C5CE7',
    accentColor: '#FD79A8',
    bgBase: '#1C0620',
    cardBg: 'rgba(40, 14, 46, 0.80)',
    cardBorder: 'rgba(255, 118, 117, 0.28)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#FFB8D2',
  },
  {
    id: 'clouds',
    name: 'Clouds',
    description: 'Slowly moving clouds',
    animationLabel: 'Slowly moving clouds',
    primaryColor: '#81ECEC',
    secondaryColor: '#74B9FF',
    accentColor: '#E0F2FE',
    bgBase: '#101B2E',
    cardBg: 'rgba(24, 38, 60, 0.80)',
    cardBorder: 'rgba(129, 236, 236, 0.25)',
    textColor: '#FFFFFF',
    textSecondaryColor: '#BAE6FD',
  },
];

const LEGACY_MAP: Record<string, string> = {
  cinema: 'cyberpunk',
  library: 'clouds',
  vinyl: 'particles',
  arcade: 'vaporwave',
  garage: 'liquid_metal',
  atlas: 'ocean',
  kitchen: 'aurora',
  stadium: 'matrix',
  titanium: 'liquid_metal',
  cosmic: 'nebula',
};

export function getProfileTheme(themeId?: string | null): ProfileTheme | null {
  if (!themeId || themeId === 'system' || themeId === 'default' || themeId === 'none') {
    return null;
  }
  const mappedId = LEGACY_MAP[themeId] || themeId;
  const found = PROFILE_THEMES.find(t => t.id === mappedId);
  return found || null;
}
